import { useState } from "react";
import "./App.css";
import axios from "axios";
import { jsPDF } from "jspdf";

function App() {
  const [url, setUrl] = useState("");
  const [auditedUrl, setAuditedUrl] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [auditTime, setAuditTime] = useState("");
  const [performance, setPerformance] = useState("");

  const handleAudit = async () => {
    try {
      setLoading(true);
      setError("");
      setResult(null);

      const response = await axios.post(
        "https://pagepulse-ifnx.onrender.com/audit",
        {
          url,
        }
      );

      setResult(response.data);
      setAuditedUrl(url);
      setAuditTime(new Date().toLocaleString());

      const time = parseInt(response.data.responseTime);

      if (time < 300) {
        setPerformance("🟢 Excellent");
      } else if (time < 700) {
        setPerformance("🟡 Good");
      } else {
        setPerformance("🔴 Slow");
      }

      setUrl("");

    } catch (error) {

      setResult(null);

      if (error.response?.data?.error) {
        setError(error.response.data.error);
      } else {
        setError(error.message || "Unable to connect to the server.");
      }

    } finally {

      setLoading(false);

    }
  };

  const downloadReport = () => {

    if (!result) return;

    const doc = new jsPDF();

    // ===== Header =====
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("PAGE PULSE", 20, 18);

    doc.setFontSize(12);
    doc.text("Website Audit Report", 20, 25);

    // ===== Body =====
    doc.setTextColor(0, 0, 0);

    let y = 45;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Audit Information", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    doc.text(`Website: ${auditedUrl}`, 20, y);
    y += 8;

    doc.text(`Audit Time: ${auditTime}`, 20, y);
    y += 8;

    doc.text(`Status: ${result.status}`, 20, y);
    y += 8;

    doc.text(`Response Time: ${result.responseTime}`, 20, y);
    y += 8;

    doc.text(`Performance: ${performance}`, 20, y);
    y += 8;

    doc.text(`H1 Count: ${result.h1Count}`, 20, y);
    y += 8;

    doc.text(`Word Count: ${result.wordCount}`, 20, y);

    y += 12;

    doc.setDrawColor(180);
    doc.line(20, y, 190, y);

    y += 12;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Title", 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const titleLines = doc.splitTextToSize(
      result.title || "N/A",
      170
    );

    doc.text(titleLines, 20, y);

    y += titleLines.length * 6 + 8;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Description", 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const descLines = doc.splitTextToSize(
      result.description || "No description available.",
      170
    );

    doc.text(descLines, 20, y);

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
      "Generated by Page Pulse",
      105,
      285,
      {
        align: "center",
      }
    );

    doc.save("PagePulse_Audit_Report.pdf");
  };
    return (
    <div className="container">
      <div className="card">
        <h1>🌐 Page Pulse</h1>

        <p className="subtitle">
          Audit any website in seconds
        </p>

        <label>Website URL</label>

        <input
          type="text"
          placeholder="https://github.com"
          value={url}
          disabled={loading}
          onChange={(e) => setUrl(e.target.value)}
        />

        <button
          onClick={handleAudit}
          disabled={loading}
        >
          {loading ? "Auditing..." : "Audit Website"}
        </button>

        <button
          className="clear-btn"
          onClick={() => {
            setUrl("");
            setAuditedUrl("");
            setResult(null);
            setError("");
            setPerformance("");
            setAuditTime("");
          }}
        >
          Clear
        </button>

        {error && (
          <div className="error">
            {error}
          </div>
        )}

        {result && (
          <div className="result">

            <h2>📊 Audit Report</h2>

            <button
              className="download-btn"
              onClick={downloadReport}
            >
              📥 Download PDF
            </button>

            <div className="info-card">
              <h3>🌐 Website</h3>
              <p>{auditedUrl}</p>
            </div>

            <div className="stats">

              <div className="stat-card">
                <h3>Status</h3>
                <p>{result.status}</p>
              </div>

              <div className="stat-card">
                <h3>Response Time</h3>
                <p>{result.responseTime}</p>
              </div>

            </div>

            <div className="stats">

              <div className="stat-card">
                <h3>Performance</h3>
                <p>{performance}</p>
              </div>

              <div className="stat-card">
                <h3>Audit Time</h3>
                <p style={{ fontSize: "14px" }}>
                  {auditTime}
                </p>
              </div>

            </div>

            <div className="info-card">
              <h3>Title</h3>
              <p>{result.title}</p>
            </div>

            <div className="info-card">
              <h3>Description</h3>
              <p>{result.description}</p>
            </div>

            <div className="stats">

              <div className="stat-card">
                <h3>H1 Count</h3>
                <p>{result.h1Count}</p>
              </div>

              <div className="stat-card">
                <h3>Word Count</h3>
                <p>{result.wordCount}</p>
              </div>

            </div>

          </div>
        )}

      </div>
    </div>
  );
}

export default App;